### ISSUE TITLE
No texture result!

### ISSUE THREAD

**Issue by ErythroCraft** [zhenghanlee/CustomShop#1]
Hi.

I got a problem with your plugin or I didn't understand the wiki.

I installed the plugin and was updating the rcs.
This is the result:

![2021-06-16_20 00 04](https://user-images.githubusercontent.com/76217862/122270850-0c0adf00-cedf-11eb-8589-9f36a09327a9.png)

**Comment by zhenghanlee** [comment]
Do you have customshop's resource pack loaded? Are you using ItemsAdder?

**Comment by zhenghanlee** [comment]
> Hi.
> 
> I got a problem with your plugin or I didn't understand the wiki.
> 
> I installed the plugin and was updating the rcs.
> This is the result:
> 
> ![2021-06-16_20 00 04](https://user-images.githubusercontent.com/76217862/122270850-0c0adf00-cedf-11eb-8589-9f36a09327a9.png)

Do you have customshop's resource pack loaded? Are you using ItemsAdder?

**Comment by zhenghanlee** [comment]
No report of similar issue or reply to the thread. Closing issue for now.
